
name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install -U coverage flake8

    - name: Run tests
      run: |
        coverage run --include="stalib/*.py" -m pytest

    - name: Check coverage
      run: |
        coverage report --show-missing --fail-under=99.9
        
    - name: Build packages
      run: |
        pip install -U twine wheel
        python setup.py sdist bdist_wheel
        twine check dist/*

    - name: Upload packages

      uses: actions/upload-artifact@v2
      with:
        name: stalib
        path: dist/*